# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://survya.com
enforce_ssl: survya.com
title: survya Singh
subtitle: 
author: Survya Singh
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"